import Head from "next/head";
import Link from 'next/link'
import React from "react";
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next K</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className='border-b p-6'>
        <p className='text-4xl font-bold'>Sign Message</p>
        <Link href="/"><a className='mr-4 text-cyan-800'>Home</a></Link>
        <Link href="/sign"><a className='mr-4 text-cyan-800'>sign</a></Link>
        <Link href="/verify"><a className='mr-4 text-cyan-800'>verify</a></Link>
      </nav>
      <Component {...pageProps} />
    </React.Fragment>
  )
}

export default MyApp
